name: Deploy via Password

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          port: 22
          script_stop: true # This stops the script if any command fails
          script: |
            cd /home/jarvis/Project
            # This configures the remote to use your token for this specific pull
            git pull https://${{ secrets.GH_PAT }}@github.com/HashimHilal-QUT/AIML_Hackathon_Jarvis.git main